apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include "kogger-service.name" . }}-cj"
  labels:
{{ include "kogger-service.labels" . | indent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
{{ include "kogger-service.labels" . | indent 12 }}
        spec:
          serviceAccountName: "{{ include "kogger-service.name" . }}-sa"
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          restartPolicy: OnFailure
          containers:
          - name: {{ include "kogger-service.name" . }}
            image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- with .Values.securityContext }}
            securityContext:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            env:
            - name: CRONJOB
              value: "true"
            envFrom:
            - configMapRef:
                name: {{ include "kogger-service.name" . }}-cm
            {{- if .Values.lifecycle }}
            lifecycle:
              {{- if .Values.lifecycle.preStop }}
              preStop:
                {{- toYaml .Values.lifecycle.preStop | nindent 16 }}
              {{- end }}
            {{- end }}
            {{- if .Values.resources }}
            resources:
              {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}