// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: koggerservice.proto

package koggerservicerpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KoggerService_GetNamespaces_FullMethodName = "/koggerservicerpc.KoggerService/GetNamespaces"
	KoggerService_ListResources_FullMethodName = "/koggerservicerpc.KoggerService/ListResources"
	KoggerService_GetResource_FullMethodName   = "/koggerservicerpc.KoggerService/GetResource"
	KoggerService_GetLogs_FullMethodName       = "/koggerservicerpc.KoggerService/GetLogs"
)

// KoggerServiceClient is the client API for KoggerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KoggerServiceClient interface {
	GetNamespaces(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Namespaces, error)
	ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ResourcesResponse, error)
	GetResource(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*Resource, error)
	GetLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*Logs, error)
}

type koggerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKoggerServiceClient(cc grpc.ClientConnInterface) KoggerServiceClient {
	return &koggerServiceClient{cc}
}

func (c *koggerServiceClient) GetNamespaces(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Namespaces, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Namespaces)
	err := c.cc.Invoke(ctx, KoggerService_GetNamespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koggerServiceClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourcesResponse)
	err := c.cc.Invoke(ctx, KoggerService_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koggerServiceClient) GetResource(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*Resource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Resource)
	err := c.cc.Invoke(ctx, KoggerService_GetResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koggerServiceClient) GetLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*Logs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Logs)
	err := c.cc.Invoke(ctx, KoggerService_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KoggerServiceServer is the server API for KoggerService service.
// All implementations must embed UnimplementedKoggerServiceServer
// for forward compatibility.
type KoggerServiceServer interface {
	GetNamespaces(context.Context, *Void) (*Namespaces, error)
	ListResources(context.Context, *ListResourcesRequest) (*ResourcesResponse, error)
	GetResource(context.Context, *ResourceRequest) (*Resource, error)
	GetLogs(context.Context, *LogsRequest) (*Logs, error)
	mustEmbedUnimplementedKoggerServiceServer()
}

// UnimplementedKoggerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKoggerServiceServer struct{}

func (UnimplementedKoggerServiceServer) GetNamespaces(context.Context, *Void) (*Namespaces, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNamespaces not implemented")
}
func (UnimplementedKoggerServiceServer) ListResources(context.Context, *ListResourcesRequest) (*ResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedKoggerServiceServer) GetResource(context.Context, *ResourceRequest) (*Resource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResource not implemented")
}
func (UnimplementedKoggerServiceServer) GetLogs(context.Context, *LogsRequest) (*Logs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedKoggerServiceServer) mustEmbedUnimplementedKoggerServiceServer() {}
func (UnimplementedKoggerServiceServer) testEmbeddedByValue()                       {}

// UnsafeKoggerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KoggerServiceServer will
// result in compilation errors.
type UnsafeKoggerServiceServer interface {
	mustEmbedUnimplementedKoggerServiceServer()
}

func RegisterKoggerServiceServer(s grpc.ServiceRegistrar, srv KoggerServiceServer) {
	// If the following call pancis, it indicates UnimplementedKoggerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KoggerService_ServiceDesc, srv)
}

func _KoggerService_GetNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoggerServiceServer).GetNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KoggerService_GetNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoggerServiceServer).GetNamespaces(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _KoggerService_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoggerServiceServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KoggerService_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoggerServiceServer).ListResources(ctx, req.(*ListResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KoggerService_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoggerServiceServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KoggerService_GetResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoggerServiceServer).GetResource(ctx, req.(*ResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KoggerService_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoggerServiceServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KoggerService_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoggerServiceServer).GetLogs(ctx, req.(*LogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KoggerService_ServiceDesc is the grpc.ServiceDesc for KoggerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KoggerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "koggerservicerpc.KoggerService",
	HandlerType: (*KoggerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNamespaces",
			Handler:    _KoggerService_GetNamespaces_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _KoggerService_ListResources_Handler,
		},
		{
			MethodName: "GetResource",
			Handler:    _KoggerService_GetResource_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _KoggerService_GetLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "koggerservice.proto",
}
